### ISSUE TITLE
Please upgrade to ZT_VERSION=1.5.0

### ISSUE THREAD

**Issue by diwu1989** [henrist/zerotier-one-docker#4]
new version of zerotier with much better performance, please upgrade :) and publish new image

**Comment by henrist** [comment]
Thanks for your issue!

I see 1.5.0 is listed as a beta/pre-release according to https://github.com/zerotier/ZeroTierOne/releases

I think maybe we should wait for the 1.6.0 release before updating the latest tag.

How about we either set up a "beta" tag, or add a zerotier-specific tag such as `henrist/zerotier-one:1.5`?

**Comment by diwu1989** [comment]
Version specific tag would be great, thank you!

**Comment by diwu1989** [comment]
Version 1.6 is officially released, can we upgrade and republish image?

**Comment by henrist** [comment]
Thanks for the heads up - and apologize for not following up on your previous request.

The image is now updated to 1.6.0 + an unreleased bugfix commit.

I've also added 1.4 and 1.6 Docker tags for those who want to "pin" their version for some reason.
